import React, { createContext, useContext, useState, useEffect } from 'react';

interface Language {
  code: string;
  name: string;
  nativeName: string;
}

interface LanguageContextType {
  currentLanguage: string;
  setLanguage: (code: string) => void;
  t: (key: string) => string;
  languages: Language[];
}

const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'es', name: 'Spanish', nativeName: 'Español' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português' },
  { code: 'zh', name: 'Chinese', nativeName: '中文' },
  { code: 'fr', name: 'French', nativeName: 'Français' },
  { code: 'de', name: 'German', nativeName: 'Deutsch' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano' },
  { code: 'ko', name: 'Korean', nativeName: '한국어' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili' },
  { code: 'af', name: 'Afrikaans', nativeName: 'Afrikaans' },
];

const translations: Record<string, Record<string, string>> = {
  en: {
    // App Header & Navigation
    'app.title': 'SmartNomad',
    'app.tagline': 'Your Digital Assistant for Global Living',
    'header.profile': 'Profile',
    'header.profile_settings': 'Profile Settings',
    'header.app_settings': 'App Settings',
    'header.upgrade_plan': 'Upgrade Plan',
    'header.privacy_data': 'Privacy & Data',
    'header.sign_out': 'Sign Out',
    'nav.dashboard': 'Dashboard',
    'nav.tracking': 'Travel Tracking',
    'nav.tax': 'Tax Residency',
    'nav.visas': 'Visa Manager',
    'nav.documents': 'Documents',
    'nav.health': 'Health & Vaccines',
    'nav.news': 'Travel News',
    'nav.alerts': 'Smart Alerts',
    'nav.services': 'Travel Services',
    'nav.settings': 'Settings',
    'nav.help': 'Help & Support',
    'nav.footer_version': 'TravelTracker v2.0',
    'nav.footer_tagline': 'Stay compliant worldwide',
    
    // Dashboard Stats
    'stats.countries_tracked': 'Countries Tracked',
    'stats.active_destinations': 'Active destinations',
    'stats.active_tracking': 'Active Tracking',
    'stats.with_recorded_visits': 'With recorded visits',
    'stats.critical_alerts': 'Critical Alerts',
    'stats.require_attention': 'Require attention',
    'stats.warnings': 'Warnings',
    'stats.urgent': 'Urgent',
    'stats.monitor_closely': 'Monitor closely',
    
    // Quick Actions
    'quick.title': 'Quick Actions',
    'quick.add_country': 'Add Country',
    'quick.add_country_desc': 'Track a new destination',
    'quick.upload_documents': 'Upload Documents',
    'quick.upload_documents_desc': 'Add passport & visas',
    'quick.check_visas': 'Check Visas',
    'quick.check_visas_desc': 'View visa status',
    'quick.view_alerts': 'View Alerts',
    'quick.view_alerts_desc': 'Check notifications',
    'quick.ai_doctor': 'AI Travel Doctor',
    'quick.ai_doctor_desc': 'Health advice & vaccines',
    'quick.ai_lawyer': 'AI Travel Lawyer',
    'quick.ai_lawyer_desc': 'Legal guidance',
    'quick.ai_visa_helper': 'AI Visa Helper',
    'quick.ai_visa_helper_desc': 'Visa requirements',
    'quick.ai_restaurant': 'AI Restaurant Booking',
    'quick.ai_restaurant_desc': 'Find & book nearby',
    'quick.esim': 'eSIM Services',
    'quick.esim_desc': 'Stay connected worldwide',
    'quick.embassy': 'Embassy Directory',
    'quick.embassy_desc': 'Official contacts',
    
    // Embassy Directory
    'embassy.title': 'Embassy Directory',
    'embassy.description': 'Access official embassy websites and travel advisories from major countries',
    'embassy.visit_website': 'Visit Website',
    'embassy.travel_advice': 'Travel Advice',
    'embassy.register': 'Register Travel',
    'embassy.tip': 'Tip: Register your travel with your embassy for emergency assistance and safety updates',
    
    // AI Assistant
    'ai.title': 'AI Travel Assistant',
    'ai.typing': 'AI is typing...',
    'ai.greeting': 'Hello! I\'m your AI Travel Assistant. How can I help you today?',
    'ai.visa_response': 'Based on your {count} tracked countries, I can help you with visa requirements and applications.',
    'ai.booking_response': 'I can help you find and book the best restaurants in your current location.',
    'ai.weather_response': 'I can provide weather information for all {count} countries you\'re tracking.',
    'ai.tax_response': 'I can assist with tax residency questions and compliance requirements.',
    'ai.alert_response': 'Your {tier} plan includes smart alerts and notifications to keep you informed.',
    'ai.help_response': 'I can help with visa requirements, tax residency, travel planning, and much more!',
    
    // Document Tracker
    'doc.title': 'Document Tracker',
    'doc.track_description': 'Keep track of your important travel documents and expiry dates',
    'doc.passports': 'Passports',
    'doc.licenses': 'Licenses',
    'doc.no_passports': 'No passports added yet',
    'doc.add_passport': 'Add Passport',
    'doc.add_license': 'Add License',
    'doc.country_state': 'Country/State',
    'doc.license_class': 'License Class',
    'doc.issue_date': 'Issue Date',
    'doc.expiry_date': 'Expiry Date',
    'doc.issuing_authority': 'Issuing Authority',
    'doc.notes': 'Notes',
    
    // Expense Tracker
    'expense.title': 'Business Expense Tracker',
    
    // Smart Alerts
    'alerts.title': 'Smart Alerts & Notifications',
    'alerts.settings': 'Settings',
    
    // Passport Manager
    'passport.title': 'Passport Manager',
    
    // User Profile
    'profile.title': 'User Profile & Preferences',
    
    // Tax Residency
    'tax.title': 'Tax Residency & Compliance Center',
    'tax.global_overview': 'Global Overview',
    'tax.united_states': 'United States',
    'tax.canada': 'Canada',
    'tax.select_jurisdiction': 'Select Jurisdiction',
    
    // Country Card
    'card.limit_exceeded': 'Limit Exceeded',
    'card.critical': 'Critical',
    'card.warning': 'Warning',
    'card.monitor': 'Monitor',
    'card.safe': 'Safe',
    'card.entries': 'Entries',
    'card.current': 'Current',
    'card.count_travel_days': 'Count Travel Days',
    'card.on': 'ON',
    'card.off': 'OFF',
    'card.tax_residence_status': 'Tax Residence Status',
    'card.days_left': 'days left',
    'card.days_this_year': 'days this year',
    'card.days_progress': 'Days Progress',
    'card.days_spent': 'Days Spent',
    'card.remaining': 'remaining',
    'card.day_limit': 'Day Limit',
    'card.this_year': 'This Year',
    'card.total_days': 'Total Days',
    'card.edit_limit': 'Edit Limit',
    'card.reset': 'Reset',
    
    // Add Country Modal
    'addCountry.title': 'Add Country to Track',
    
    // Circular Dashboard
    'circularDashboard.title': 'Travel Overview',
    
    // Toast Messages
    'toast.countryAdded': 'Country Added',
    'toast.countryAddedDesc': '{country} has been added to your tracking list',
    'toast.countryRemoved': 'Country Removed',
    'toast.countryRemovedDesc': 'Country has been removed from tracking',
    'toast.locationConfirmed': 'Location Confirmed',
    'toast.locationConfirmedDesc': 'Your location has been confirmed',
    'toast.locationCorrection': 'Location Needs Correction',
    'toast.locationCorrectionDesc': 'Please update your location manually',
    'toast.vpnInstructions': 'VPN Detected',
    'toast.vpnInstructionsDesc': 'Please disable VPN for accurate tracking',
    'toast.planUpgraded': 'Plan Upgraded',
    'toast.planUpgradedDesc': 'Successfully upgraded to {tier} plan',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.free': 'Free',
  },
  es: {
    // Header
    'app.title': 'TravelTracker',
    'app.tagline': 'Tu compañero global de viajes',
    'header.profile': 'Perfil',
    'header.profile_settings': 'Configuración del perfil',
    'header.app_settings': 'Configuración de la aplicación',
    'header.upgrade_plan': 'Actualizar plan',
    'header.privacy_data': 'Privacidad y datos',
    'header.sign_out': 'Cerrar sesión',
    'nav.dashboard': 'Panel',
    'nav.tracking': 'Seguimiento de viajes',
    'nav.tax': 'Residencia fiscal',
    'nav.visas': 'Gestor de visas',
    'nav.documents': 'Documentos',
    'nav.health': 'Salud y vacunas',
    'nav.news': 'Noticias de viajes',
    'nav.alerts': 'Alertas inteligentes',
    'nav.services': 'Servicios de viaje',
    'nav.settings': 'Configuración',
    'nav.help': 'Ayuda y soporte',
    'nav.footer_version': 'TravelTracker v2.0',
    'nav.footer_tagline': 'Mantente conforme en todo el mundo',
    
    // Dashboard Stats
    'stats.countries_tracked': 'Países rastreados',
    'stats.active_destinations': 'Destinos activos',
    'stats.active_tracking': 'Rastreo Activo',
    'stats.with_recorded_visits': 'Con visitas registradas',
    'stats.critical_alerts': 'Alertas críticas',
    'stats.require_attention': 'Requieren atención',
    'stats.warnings': 'Advertencias',
    'stats.urgent': 'Urgente',
    'stats.monitor_closely': 'Monitorear de cerca',
    
    // Quick Actions
    'quick.title': 'Acciones rápidas',
    'quick.add_country': 'Agregar País',
    'quick.add_country_desc': 'Rastrear nuevo destino',
    'quick.upload_documents': 'Subir Documentos',
    'quick.upload_documents_desc': 'Añadir pasaporte y visas',
    'quick.check_visas': 'Verificar Visas',
    'quick.check_visas_desc': 'Ver estado de visa',
    'quick.view_alerts': 'Ver Alertas',
    'quick.view_alerts_desc': 'Revisar notificaciones',
    'quick.ai_doctor': 'Doctor de Viaje IA',
    'quick.ai_doctor_desc': 'Consejos de salud y vacunas',
    'quick.ai_lawyer': 'Abogado de Viaje IA',
    'quick.ai_lawyer_desc': 'Orientación legal',
    'quick.ai_visa_helper': 'Asistente de Visa IA',
    'quick.ai_visa_helper_desc': 'Requisitos de visa',
    'quick.ai_restaurant': 'Reserva de Restaurante IA',
    'quick.ai_restaurant_desc': 'Buscar y reservar cerca',
    'quick.esim': 'Servicios eSIM',
    'quick.esim_desc': 'Conéctate en todo el mundo',
    'quick.embassy': 'Directorio de Embajadas',
    'quick.embassy_desc': 'Contactos oficiales',
    
    // Embassy Directory
    'embassy.title': 'Directorio de Embajadas',
    'embassy.description': 'Acceda a sitios web oficiales de embajadas y avisos de viaje de países principales',
    'embassy.visit_website': 'Visitar Sitio Web',
    'embassy.travel_advice': 'Consejos de Viaje',
    'embassy.register': 'Registrar Viaje',
    'embassy.tip': 'Consejo: Registre su viaje con su embajada para asistencia de emergencia y actualizaciones de seguridad',
    
    // AI Assistant
    'ai.title': 'Asistente de viaje IA',
    'ai.typing': 'IA está escribiendo...',
    'ai.greeting': '¡Hola! Soy tu Asistente de Viaje IA. ¿Cómo puedo ayudarte hoy?',
    'ai.visa_response': 'Basado en tus {count} países rastreados, puedo ayudarte con requisitos de visa y solicitudes.',
    'ai.booking_response': 'Puedo ayudarte a encontrar y reservar los mejores restaurantes en tu ubicación actual.',
    'ai.weather_response': 'Puedo proporcionar información meteorológica para todos los {count} países que estás rastreando.',
    'ai.tax_response': 'Puedo asistir con preguntas de residencia fiscal y requisitos de cumplimiento.',
    'ai.alert_response': 'Tu plan {tier} incluye alertas inteligentes y notificaciones para mantenerte informado.',
    'ai.help_response': '¡Puedo ayudar con requisitos de visa, residencia fiscal, planificación de viajes y mucho más!',
    
    // Document Tracker
    'doc.title': 'Rastreador de documentos',
    'doc.track_description': 'Mantenga un registro de sus documentos de viaje importantes y fechas de vencimiento',
    'doc.passports': 'Pasaportes',
    'doc.licenses': 'Licencias',
    'doc.no_passports': 'Aún no se han agregado pasaportes',
    'doc.add_passport': 'Agregar Pasaporte',
    'doc.add_license': 'Agregar Licencia',
    'doc.country_state': 'País/Estado',
    'doc.license_class': 'Clase de Licencia',
    'doc.issue_date': 'Fecha de Emisión',
    'doc.expiry_date': 'Fecha de Vencimiento',
    'doc.issuing_authority': 'Autoridad Emisora',
    'doc.notes': 'Notas',
    
    // Expense Tracker
    'expense.title': 'Rastreador de gastos empresariales',
    
    // Smart Alerts
    'alerts.title': 'Alertas inteligentes y notificaciones',
    'alerts.settings': 'Configuración',
    
    // Passport Manager
    'passport.title': 'Gestor de pasaportes',
    
    // User Profile
    'profile.title': 'Perfil de usuario y preferencias',
    
    // Tax Residency
    'tax.title': 'Centro de residencia fiscal y cumplimiento',
    'tax.global_overview': 'Resumen Global',
    'tax.united_states': 'Estados Unidos',
    'tax.canada': 'Canadá',
    'tax.select_jurisdiction': 'Seleccionar Jurisdicción',
    
    // Country Card
    'card.limit_exceeded': 'Límite Excedido',
    'card.critical': 'Crítico',
    'card.warning': 'Advertencia',
    'card.monitor': 'Monitorear',
    'card.safe': 'Seguro',
    'card.entries': 'Entradas',
    'card.current': 'Actual',
    'card.count_travel_days': 'Contar Días de Viaje',
    'card.on': 'ACTIVADO',
    'card.off': 'DESACTIVADO',
    'card.tax_residence_status': 'Estado de Residencia Fiscal',
    'card.days_left': 'días restantes',
    'card.days_this_year': 'días este año',
    'card.days_progress': 'Progreso de Días',
    'card.days_spent': 'Días Gastados',
    'card.remaining': 'restantes',
    'card.day_limit': 'Límite de Días',
    'card.this_year': 'Este Año',
    'card.total_days': 'Días Totales',
    'card.edit_limit': 'Editar Límite',
    'card.reset': 'Reiniciar',
    
    // Add Country Modal
    'addCountry.title': 'Agregar País para Rastrear',
    
    // Circular Dashboard
    'circularDashboard.title': 'Resumen de Viajes',
    
    // Toast Messages
    'toast.countryAdded': 'País Agregado',
    'toast.countryAddedDesc': '{country} ha sido agregado a tu lista de rastreo',
    'toast.countryRemoved': 'País Eliminado',
    'toast.countryRemovedDesc': 'El país ha sido eliminado del rastreo',
    'toast.locationConfirmed': 'Ubicación Confirmada',
    'toast.locationConfirmedDesc': 'Tu ubicación ha sido confirmada',
    'toast.locationCorrection': 'La Ubicación Necesita Corrección',
    'toast.locationCorrectionDesc': 'Por favor actualiza tu ubicación manualmente',
    'toast.vpnInstructions': 'VPN Detectada',
    'toast.vpnInstructionsDesc': 'Por favor desactiva la VPN para un rastreo preciso',
    'toast.planUpgraded': 'Plan Actualizado',
    'toast.planUpgradedDesc': 'Actualizado exitosamente al plan {tier}',
    
    // Common
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.close': 'Cerrar',
    'common.free': 'Gratis',
  },
  pt: {
    // Header
    'app.title': 'TravelTracker',
    'app.tagline': 'Seu companheiro global de viagens',
    'header.profile': 'Perfil',
    'header.profile_settings': 'Configurações do perfil',
    'header.app_settings': 'Configurações do aplicativo',
    'header.upgrade_plan': 'Atualizar plano',
    'header.privacy_data': 'Privacidade e dados',
    'header.sign_out': 'Sair',
    'nav.dashboard': 'Painel',
    'nav.tracking': 'Rastreamento de viagens',
    'nav.tax': 'Residência fiscal',
    'nav.visas': 'Gerenciador de vistos',
    'nav.documents': 'Documentos',
    'nav.health': 'Saúde e vacinas',
    'nav.news': 'Notícias de viagens',
    'nav.alerts': 'Alertas inteligentes',
    'nav.services': 'Serviços de viagem',
    'nav.settings': 'Configurações',
    'nav.help': 'Ajuda e suporte',
    'nav.footer_version': 'TravelTracker v2.0',
    'nav.footer_tagline': 'Mantenha-se conforme em todo o mundo',
    
    // Dashboard Stats
    'stats.countries_tracked': 'Países rastreados',
    'stats.active_destinations': 'Destinos ativos',
    'stats.active_tracking': 'Rastreamento Ativo',
    'stats.with_recorded_visits': 'Com visitas registradas',
    'stats.critical_alerts': 'Alertas críticos',
    'stats.require_attention': 'Requerem atenção',
    'stats.warnings': 'Avisos',
    'stats.urgent': 'Urgente',
    'stats.monitor_closely': 'Monitorar de perto',
    
    // Quick Actions
    'quick.title': 'Ações rápidas',
    'quick.add_country': 'Adicionar País',
    'quick.add_country_desc': 'Rastrear novo destino',
    'quick.upload_documents': 'Enviar Documentos',
    'quick.upload_documents_desc': 'Adicionar passaporte e vistos',
    'quick.check_visas': 'Verificar Vistos',
    'quick.check_visas_desc': 'Ver status do visto',
    'quick.view_alerts': 'Ver Alertas',
    'quick.view_alerts_desc': 'Verificar notificações',
    'quick.ai_doctor': 'Médico de Viagem IA',
    'quick.ai_doctor_desc': 'Conselhos de saúde e vacinas',
    'quick.ai_lawyer': 'Advogado de Viagem IA',
    'quick.ai_lawyer_desc': 'Orientação jurídica',
    'quick.ai_visa_helper': 'Assistente de Visto IA',
    'quick.ai_visa_helper_desc': 'Requisitos de visto',
    'quick.ai_restaurant': 'Reserva de Restaurante IA',
    'quick.ai_restaurant_desc': 'Encontrar e reservar perto',
    'quick.esim': 'Serviços eSIM',
    'quick.esim_desc': 'Conecte-se em todo o mundo',
    'quick.embassy': 'Diretório de Embaixadas',
    'quick.embassy_desc': 'Contatos oficiais',
    
    // Embassy Directory
    'embassy.title': 'Diretório de Embaixadas',
    'embassy.description': 'Acesse sites oficiais de embaixadas e avisos de viagem de países principais',
    'embassy.visit_website': 'Visitar Site',
    'embassy.travel_advice': 'Conselhos de Viagem',
    'embassy.register': 'Registrar Viagem',
    'embassy.tip': 'Dica: Registre sua viagem com sua embaixada para assistência de emergência e atualizações de segurança',
    
    // AI Assistant
    'ai.title': 'Assistente de viagem IA',
    'ai.typing': 'IA está digitando...',
    'ai.greeting': 'Olá! Sou seu Assistente de Viagem IA. Como posso ajudá-lo hoje?',
    'ai.visa_response': 'Com base em seus {count} países rastreados, posso ajudá-lo com requisitos e solicitações de visto.',
    'ai.booking_response': 'Posso ajudá-lo a encontrar e reservar os melhores restaurantes em sua localização atual.',
    'ai.weather_response': 'Posso fornecer informações meteorológicas para todos os {count} países que você está rastreando.',
    'ai.tax_response': 'Posso ajudar com questões de residência fiscal e requisitos de conformidade.',
    'ai.alert_response': 'Seu plano {tier} inclui alertas inteligentes e notificações para mantê-lo informado.',
    'ai.help_response': 'Posso ajudar com requisitos de visto, residência fiscal, planejamento de viagens e muito mais!',
    
    // Document Tracker
    'doc.title': 'Rastreador de documentos',
    'doc.track_description': 'Acompanhe seus documentos de viagem importantes e datas de validade',
    'doc.passports': 'Passaportes',
    'doc.licenses': 'Licenças',
    'doc.no_passports': 'Nenhum passaporte adicionado ainda',
    'doc.add_passport': 'Adicionar Passaporte',
    'doc.add_license': 'Adicionar Licença',
    'doc.country_state': 'País/Estado',
    'doc.license_class': 'Classe da Licença',
    'doc.issue_date': 'Data de Emissão',
    'doc.expiry_date': 'Data de Validade',
    'doc.issuing_authority': 'Autoridade Emissora',
    'doc.notes': 'Notas',
    
    // Expense Tracker
    'expense.title': 'Rastreador de despesas empresariais',
    
    // Smart Alerts
    'alerts.title': 'Alertas inteligentes e notificações',
    'alerts.settings': 'Configurações',
    
    // Passport Manager
    'passport.title': 'Gerenciador de passaportes',
    
    // User Profile
    'profile.title': 'Perfil de usuário e preferências',
    
    // Tax Residency
    'tax.title': 'Centro de residência fiscal e conformidade',
    'tax.global_overview': 'Visão Geral Global',
    'tax.united_states': 'Estados Unidos',
    'tax.canada': 'Canadá',
    'tax.select_jurisdiction': 'Selecionar Jurisdição',
    
    // Country Card
    'card.limit_exceeded': 'Limite Excedido',
    'card.critical': 'Crítico',
    'card.warning': 'Aviso',
    'card.monitor': 'Monitorar',
    'card.safe': 'Seguro',
    'card.entries': 'Entradas',
    'card.current': 'Atual',
    'card.count_travel_days': 'Contar Dias de Viagem',
    'card.on': 'LIGADO',
    'card.off': 'DESLIGADO',
    'card.tax_residence_status': 'Status de Residência Fiscal',
    'card.days_left': 'dias restantes',
    'card.days_this_year': 'dias este ano',
    'card.days_progress': 'Progresso de Dias',
    'card.days_spent': 'Dias Gastos',
    'card.remaining': 'restantes',
    'card.day_limit': 'Limite de Dias',
    'card.this_year': 'Este Ano',
    'card.total_days': 'Dias Totais',
    'card.edit_limit': 'Editar Limite',
    'card.reset': 'Reiniciar',
    
    // Add Country Modal
    'addCountry.title': 'Adicionar País para Rastrear',
    
    // Circular Dashboard
    'circularDashboard.title': 'Visão Geral de Viagens',
    
    // Toast Messages
    'toast.countryAdded': 'País Adicionado',
    'toast.countryAddedDesc': '{country} foi adicionado à sua lista de rastreamento',
    'toast.countryRemoved': 'País Removido',
    'toast.countryRemovedDesc': 'O país foi removido do rastreamento',
    'toast.locationConfirmed': 'Localização Confirmada',
    'toast.locationConfirmedDesc': 'Sua localização foi confirmada',
    'toast.locationCorrection': 'Localização Precisa de Correção',
    'toast.locationCorrectionDesc': 'Por favor, atualize sua localização manualmente',
    'toast.vpnInstructions': 'VPN Detectada',
    'toast.vpnInstructionsDesc': 'Por favor, desative a VPN para rastreamento preciso',
    'toast.planUpgraded': 'Plano Atualizado',
    'toast.planUpgradedDesc': 'Atualizado com sucesso para o plano {tier}',
    
    // Common
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.close': 'Fechar',
    'common.free': 'Grátis',
  },
  hi: {
    // Header
    'app.title': 'TravelTracker',
    'app.tagline': 'आपका वैश्विक यात्रा साथी',
    'header.profile': 'प्रोफ़ाइल',
    'header.profile_settings': 'प्रोफ़ाइल सेटिंग्स',
    'header.app_settings': 'ऐप सेटिंग्स',
    'header.upgrade_plan': 'प्लान अपग्रेड करें',
    'header.privacy_data': 'गोपनीयता और डेटा',
    'header.sign_out': 'साइन आउट',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.tracking': 'यात्रा ट्रैकिंग',
    'nav.tax': 'कर निवास',
    'nav.visas': 'वीज़ा प्रबंधक',
    'nav.documents': 'दस्तावेज़',
    'nav.health': 'स्वास्थ्य और टीके',
    'nav.news': 'यात्रा समाचार',
    'nav.alerts': 'स्मार्ट अलर्ट',
    'nav.services': 'यात्रा सेवाएं',
    'nav.settings': 'सेटिंग्स',
    'nav.help': 'सहायता और समर्थन',
    'nav.footer_version': 'TravelTracker v2.0',
    'nav.footer_tagline': 'दुनिया भर में अनुपालन बनाए रखें',
    
    // Dashboard Stats
    'stats.countries_tracked': 'ट्रैक किए गए देश',
    'stats.active_destinations': 'सक्रिय गंतव्य',
    'stats.active_tracking': 'सक्रिय ट्रैकिंग',
    'stats.with_recorded_visits': 'रिकॉर्ड किए गए दौरों के साथ',
    'stats.critical_alerts': 'गंभीर अलर्ट',
    'stats.require_attention': 'ध्यान देने की आवश्यकता',
    'stats.warnings': 'चेतावनी',
    'stats.urgent': 'तत्काल',
    'stats.monitor_closely': 'बारीकी से निगरानी करें',
    
    // Quick Actions
    'quick.title': 'त्वरित क्रियाएं',
    'quick.add_country': 'देश जोड़ें',
    'quick.add_country_desc': 'नया गंतव्य ट्रैक करें',
    'quick.upload_documents': 'दस्तावेज़ अपलोड करें',
    'quick.upload_documents_desc': 'पासपोर्ट और वीज़ा जोड़ें',
    'quick.check_visas': 'वीज़ा जांचें',
    'quick.check_visas_desc': 'वीज़ा स्थिति देखें',
    'quick.view_alerts': 'अलर्ट देखें',
    'quick.view_alerts_desc': 'सूचनाएं जांचें',
    'quick.ai_doctor': 'एआई यात्रा डॉक्टर',
    'quick.ai_doctor_desc': 'स्वास्थ्य सलाह और टीके',
    'quick.ai_lawyer': 'एआई यात्रा वकील',
    'quick.ai_lawyer_desc': 'कानूनी मार्गदर्शन',
    'quick.ai_visa_helper': 'एआई वीज़ा सहायक',
    'quick.ai_visa_helper_desc': 'वीज़ा आवश्यकताएं',
    'quick.ai_restaurant': 'एआई रेस्तरां बुकिंग',
    'quick.ai_restaurant_desc': 'पास में खोजें और बुक करें',
    'quick.esim': 'eSIM सेवाएं',
    'quick.esim_desc': 'दुनिया भर में जुड़े रहें',
    'quick.embassy': 'दूतावास निर्देशिका',
    'quick.embassy_desc': 'आधिकारिक संपर्क',
    
    // Embassy Directory
    'embassy.title': 'दूतावास निर्देशिका',
    'embassy.description': 'प्रमुख देशों से आधिकारिक दूतावास वेबसाइट और यात्रा सलाह तक पहुंचें',
    'embassy.visit_website': 'वेबसाइट देखें',
    'embassy.travel_advice': 'यात्रा सलाह',
    'embassy.register': 'यात्रा पंजीकृत करें',
    'embassy.tip': 'सुझाव: आपातकालीन सहायता और सुरक्षा अपडेट के लिए अपनी यात्रा को अपने दूतावास के साथ पंजीकृत करें',
    
    // AI Assistant
    'ai.title': 'एआई यात्रा सहायक',
    'ai.typing': 'एआई टाइप कर रहा है...',
    'ai.greeting': 'नमस्ते! मैं आपका एआई यात्रा सहायक हूं। आज मैं आपकी कैसे मदद कर सकता हूं?',
    'ai.visa_response': 'आपके {count} ट्रैक किए गए देशों के आधार पर, मैं वीज़ा आवश्यकताओं और आवेदनों में आपकी सहायता कर सकता हूं।',
    'ai.booking_response': 'मैं आपके वर्तमान स्थान पर सर्वोत्तम रेस्तरां खोजने और बुक करने में आपकी मदद कर सकता हूं।',
    'ai.weather_response': 'मैं आपके द्वारा ट्रैक किए जा रहे सभी {count} देशों के लिए मौसम की जानकारी प्रदान कर सकता हूं।',
    'ai.tax_response': 'मैं कर निवास प्रश्नों और अनुपालन आवश्यकताओं में सहायता कर सकता हूं।',
    'ai.alert_response': 'आपकी {tier} योजना में आपको सूचित रखने के लिए स्मार्ट अलर्ट और सूचनाएं शामिल हैं।',
    'ai.help_response': 'मैं वीज़ा आवश्यकताओं, कर निवास, यात्रा योजना और बहुत कुछ में मदद कर सकता हूं!',
    
    // Document Tracker
    'doc.title': 'दस्तावेज़ ट्रैकर',
    'doc.track_description': 'अपने महत्वपूर्ण यात्रा दस्तावेजों और समाप्ति तिथियों का ट्रैक रखें',
    'doc.passports': 'पासपोर्ट',
    'doc.licenses': 'लाइसेंस',
    'doc.no_passports': 'अभी तक कोई पासपोर्ट नहीं जोड़ा गया',
    'doc.add_passport': 'पासपोर्ट जोड़ें',
    'doc.add_license': 'लाइसेंस जोड़ें',
    'doc.country_state': 'देश/राज्य',
    'doc.license_class': 'लाइसेंस वर्ग',
    'doc.issue_date': 'जारी करने की तिथि',
    'doc.expiry_date': 'समाप्ति तिथि',
    'doc.issuing_authority': 'जारीकर्ता प्राधिकरण',
    'doc.notes': 'नोट्स',
    
    // Expense Tracker
    'expense.title': 'व्यावसायिक व्यय ट्रैकर',
    
    // Smart Alerts
    'alerts.title': 'स्मार्ट अलर्ट और सूचनाएं',
    'alerts.settings': 'सेटिंग्स',
    
    // Passport Manager
    'passport.title': 'पासपोर्ट प्रबंधक',
    
    // User Profile
    'profile.title': 'उपयोगकर्ता प्रोफ़ाइल और प्राथमिकताएं',
    
    // Tax Residency
    'tax.title': 'कर निवास और अनुपालन केंद्र',
    'tax.global_overview': 'वैश्विक अवलोकन',
    'tax.united_states': 'संयुक्त राज्य अमेरिका',
    'tax.canada': 'कनाडा',
    'tax.select_jurisdiction': 'क्षेत्राधिकार चुनें',
    
    // Country Card
    'card.limit_exceeded': 'सीमा पार',
    'card.critical': 'महत्वपूर्ण',
    'card.warning': 'चेतावनी',
    'card.monitor': 'निगरानी',
    'card.safe': 'सुरक्षित',
    'card.entries': 'प्रवेश',
    'card.current': 'वर्तमान',
    'card.count_travel_days': 'यात्रा दिनों की गणना',
    'card.on': 'चालू',
    'card.off': 'बंद',
    'card.tax_residence_status': 'कर निवास स्थिति',
    'card.days_left': 'दिन शेष',
    'card.days_this_year': 'इस वर्ष के दिन',
    'card.days_progress': 'दिनों की प्रगति',
    'card.days_spent': 'बिताए गए दिन',
    'card.remaining': 'शेष',
    'card.day_limit': 'दिन की सीमा',
    'card.this_year': 'इस वर्ष',
    'card.total_days': 'कुल दिन',
    'card.edit_limit': 'सीमा संपादित करें',
    'card.reset': 'रीसेट',
    
    // Add Country Modal
    'addCountry.title': 'ट्रैक करने के लिए देश जोड़ें',
    
    // Circular Dashboard
    'circularDashboard.title': 'यात्रा अवलोकन',
    
    // Toast Messages
    'toast.countryAdded': 'देश जोड़ा गया',
    'toast.countryAddedDesc': '{country} को आपकी ट्रैकिंग सूची में जोड़ा गया है',
    'toast.countryRemoved': 'देश हटाया गया',
    'toast.countryRemovedDesc': 'देश को ट्रैकिंग से हटा दिया गया है',
    'toast.locationConfirmed': 'स्थान की पुष्टि की गई',
    'toast.locationConfirmedDesc': 'आपके स्थान की पुष्टि हो गई है',
    'toast.locationCorrection': 'स्थान को सुधार की आवश्यकता',
    'toast.locationCorrectionDesc': 'कृपया अपने स्थान को मैन्युअल रूप से अपडेट करें',
    'toast.vpnInstructions': 'VPN का पता चला',
    'toast.vpnInstructionsDesc': 'सटीक ट्रैकिंग के लिए कृपया VPN अक्षम करें',
    'toast.planUpgraded': 'योजना अपग्रेड की गई',
    'toast.planUpgradedDesc': 'सफलतापूर्वक {tier} योजना में अपग्रेड किया गया',
    
    // Common
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.close': 'बंद करें',
    'common.free': 'मुफ्त',
  },
  sw: {
    // Header
    'app.title': 'TravelTracker',
    'app.tagline': 'Mwenzi wako wa kimataifa wa kusafiri',
    'header.profile': 'Wasifu',
    'header.profile_settings': 'Mipangilio ya Wasifu',
    'header.app_settings': 'Mipangilio ya Programu',
    'header.upgrade_plan': 'Boresha Mpango',
    'header.privacy_data': 'Faragha na Data',
    'header.sign_out': 'Toka',
    'nav.dashboard': 'Dashibodi',
    'nav.tracking': 'Ufuatiliaji wa Safari',
    'nav.tax': 'Makazi ya Kodi',
    'nav.visas': 'Meneja wa Visa',
    'nav.documents': 'Hati',
    'nav.health': 'Afya na Chanjo',
    'nav.news': 'Habari za Safari',
    'nav.alerts': 'Arifa za Akili',
    'nav.services': 'Huduma za Safari',
    'nav.settings': 'Mipangilio',
    'nav.help': 'Msaada na Usaidizi',
    'nav.footer_version': 'TravelTracker v2.0',
    'nav.footer_tagline': 'Endelea kuwa na ufuasi ulimwenguni',
    
    // Dashboard Stats
    'stats.countries_tracked': 'Nchi Zinazofuatiliwa',
    'stats.active_destinations': 'Maeneo yanayotumika',
    'stats.active_tracking': 'Ufuatiliaji Unaotumika',
    'stats.with_recorded_visits': 'Yenye ziara zilizorekodishwa',
    'stats.critical_alerts': 'Arifa Muhimu',
    'stats.require_attention': 'Inahitaji umakini',
    'stats.warnings': 'Maonyo',
    'stats.urgent': 'Dharura',
    'stats.monitor_closely': 'Fuatilia kwa karibu',
    
    // Quick Actions
    'quick.title': 'Vitendo vya Haraka',
    'quick.add_country': 'Ongeza Nchi',
    'quick.add_country_desc': 'Fuatilia mahali mpya',
    'quick.upload_documents': 'Pakia Hati',
    'quick.upload_documents_desc': 'Ongeza pasipoti na viza',
    'quick.check_visas': 'Angalia Viza',
    'quick.check_visas_desc': 'Tazama hali ya viza',
    'quick.view_alerts': 'Tazama Arifa',
    'quick.view_alerts_desc': 'Angalia taarifa',
    'quick.ai_doctor': 'Daktari wa Usafiri wa AI',
    'quick.ai_doctor_desc': 'Ushauri wa afya na chanjo',
    'quick.ai_lawyer': 'Wakili wa Usafiri wa AI',
    'quick.ai_lawyer_desc': 'Mwongozo wa kisheria',
    'quick.ai_visa_helper': 'Msaidizi wa Viza wa AI',
    'quick.ai_visa_helper_desc': 'Mahitaji ya viza',
    'quick.ai_restaurant': 'Uhifadhi wa Mkahawa wa AI',
    'quick.ai_restaurant_desc': 'Tafuta na uhifadhi karibu',
    'quick.esim': 'Huduma za eSIM',
    'quick.esim_desc': 'Endelea kuunganishwa ulimwenguni',
    'quick.embassy': 'Saraka za Ubalozi',
    'quick.embassy_desc': 'Mawasiliano rasmi',
    
    // Embassy Directory
    'embassy.title': 'Saraka za Ubalozi',
    'embassy.description': 'Fikia tovuti rasmi za ubalozi na ushauri wa safari kutoka nchi kuu',
    'embassy.visit_website': 'Tembelea Tovuti',
    'embassy.travel_advice': 'Ushauri wa Safari',
    'embassy.register': 'Sajili Safari',
    'embassy.tip': 'Kidokezo: Sajili safari yako na ubalozi wako kwa msaada wa dharura na masasisho ya usalama',
    
    // AI Assistant
    'ai.title': 'Msaidizi wa Safari wa AI',
    'ai.typing': 'AI inaandika...',
    'ai.greeting': 'Hujambo! Mimi ni Msaidizi wako wa Safari wa AI. Naweza kukusaidia vipi leo?',
    'ai.visa_response': 'Kulingana na nchi {count} unazofuatilia, naweza kukusaidia na mahitaji ya viza na maombi.',
    'ai.booking_response': 'Naweza kukusaidia kutafuta na kuhifadhi mikahawa bora katika eneo lako la sasa.',
    'ai.weather_response': 'Naweza kutoa habari za hali ya hewa kwa nchi zote {count} unazofuatilia.',
    'ai.tax_response': 'Naweza kusaidia na maswali ya makazi ya kodi na mahitaji ya kufuata sheria.',
    'ai.alert_response': 'Mpango wako wa {tier} unajumuisha arifa na taarifa za akili kukuweka umejulishwa.',
    'ai.help_response': 'Naweza kusaidia na mahitaji ya viza, makazi ya kodi, mipango ya safari na mengi zaidi!',
    
    // Document Tracker
    'doc.title': 'Kifuatiliaji cha Hati',
    'doc.track_description': 'Fuatilia hati zako muhimu za kusafiri na tarehe za kumalizika',
    'doc.passports': 'Pasi',
    'doc.licenses': 'Leseni',
    'doc.no_passports': 'Hakuna pasipoti zilizoongezwa bado',
    'doc.add_passport': 'Ongeza Pasipoti',
    'doc.add_license': 'Ongeza Leseni',
    'doc.country_state': 'Nchi/Jimbo',
    'doc.license_class': 'Darasa la Leseni',
    'doc.issue_date': 'Tarehe ya Kutolewa',
    'doc.expiry_date': 'Tarehe ya Kumalizika',
    'doc.issuing_authority': 'Mamlaka Inayotoa',
    'doc.notes': 'Maelezo',
    
    // Expense Tracker
    'expense.title': 'Kifuatiliaji cha Gharama za Biashara',
    
    // Smart Alerts
    'alerts.title': 'Arifa za Akili na Taarifa',
    'alerts.settings': 'Mipangilio',
    
    // Passport Manager
    'passport.title': 'Meneja wa Pasi',
    
    // User Profile
    'profile.title': 'Wasifu wa Mtumiaji na Mapendeleo',
    
    // Tax Residency
    'tax.title': 'Kituo cha Makazi ya Kodi na Kufuata Sheria',
    'tax.global_overview': 'Muhtasari wa Kimataifa',
    'tax.united_states': 'Marekani',
    'tax.canada': 'Kanada',
    'tax.select_jurisdiction': 'Chagua Mamlaka',
    
    // Country Card
    'card.limit_exceeded': 'Kikomo Kimezidishwa',
    'card.critical': 'Muhimu',
    'card.warning': 'Onyo',
    'card.monitor': 'Fuatilia',
    'card.safe': 'Salama',
    'card.entries': 'Kuingia',
    'card.current': 'Ya Sasa',
    'card.count_travel_days': 'Hesabu Siku za Safari',
    'card.on': 'IMEWASHWA',
    'card.off': 'IMEZIMWA',
    'card.tax_residence_status': 'Hali ya Makazi ya Kodi',
    'card.days_left': 'siku zilizobaki',
    'card.days_this_year': 'siku mwaka huu',
    'card.days_progress': 'Maendeleo ya Siku',
    'card.days_spent': 'Siku Zilizotumika',
    'card.remaining': 'zilizobaki',
    'card.day_limit': 'Kikomo cha Siku',
    'card.this_year': 'Mwaka Huu',
    'card.total_days': 'Jumla ya Siku',
    'card.edit_limit': 'Hariri Kikomo',
    'card.reset': 'Weka Upya',
    
    // Add Country Modal
    'addCountry.title': 'Ongeza Nchi ya Kufuatilia',
    
    // Circular Dashboard
    'circularDashboard.title': 'Muhtasari wa Safari',
    
    // Toast Messages
    'toast.countryAdded': 'Nchi Imeongezwa',
    'toast.countryAddedDesc': '{country} imeongezwa kwenye orodha yako ya ufuatiliaji',
    'toast.countryRemoved': 'Nchi Imeondolewa',
    'toast.countryRemovedDesc': 'Nchi imeondolewa kutoka ufuatiliaji',
    'toast.locationConfirmed': 'Eneo Limethibitishwa',
    'toast.locationConfirmedDesc': 'Eneo lako limethibitishwa',
    'toast.locationCorrection': 'Eneo Linahitaji Urekebishaji',
    'toast.locationCorrectionDesc': 'Tafadhali sasisha eneo lako mwenyewe',
    'toast.vpnInstructions': 'VPN Imegunduliwa',
    'toast.vpnInstructionsDesc': 'Tafadhali lemaza VPN kwa ufuatiliaji sahihi',
    'toast.planUpgraded': 'Mpango Umeboreshwa',
    'toast.planUpgradedDesc': 'Umefanikiwa kuboresha hadi mpango wa {tier}',
    
    // Common
    'common.save': 'Hifadhi',
    'common.cancel': 'Ghairi',
    'common.close': 'Funga',
    'common.free': 'Bure',
  },
  af: {
    // App Header & Navigation
    'app.title': 'TravelTracker',
    'app.tagline': 'Jou globale reisgenoot',
    'header.profile': 'Profiel',
    'header.profile_settings': 'Profiel Instellings',
    'header.app_settings': 'App Instellings',
    'header.upgrade_plan': 'Opgradeer Plan',
    'header.privacy_data': 'Privaatheid & Data',
    'header.sign_out': 'Teken Uit',
    'nav.dashboard': 'Dashboard',
    'nav.tracking': 'Reis Opvolging',
    'nav.tax': 'Belasting Residensie',
    'nav.visas': 'Visum Bestuurder',
    'nav.documents': 'Dokumente',
    'nav.health': 'Gesondheid & Inentings',
    'nav.news': 'Reis Nuus',
    'nav.alerts': 'Slim Kennisgewings',
    'nav.services': 'Reis Dienste',
    'nav.settings': 'Instellings',
    'nav.help': 'Hulp & Ondersteuning',
    'nav.footer_version': 'TravelTracker v2.0',
    'nav.footer_tagline': 'Bly voldoende wêreldwyd',
    
    // Dashboard Stats
    'stats.countries_tracked': 'Lande Opgevolg',
    'stats.active_destinations': 'Aktiewe bestemmings',
    'stats.critical_alerts': 'Kritieke Kennisgewings',
    'stats.require_attention': 'Vereis aandag',
    
    // Quick Actions
    'quick.title': 'Vinnige Aksies',
    'quick.add_country': 'Voeg Land By',
    'quick.add_country_desc': 'Volg nuwe bestemming',
    'quick.upload_documents': 'Laai Dokumente Op',
    'quick.upload_documents_desc': 'Voeg paspoort en visums by',
    'quick.check_visas': 'Kontroleer Visums',
    'quick.check_visas_desc': 'Bekyk visum status',
    'quick.view_alerts': 'Bekyk Kennisgewings',
    'quick.view_alerts_desc': 'Kontroleer kennisgewings',
    'quick.ai_doctor': 'KI Reisdokter',
    'quick.ai_doctor_desc': 'Gesondheidsadvies en inentings',
    'quick.ai_lawyer': 'KI Reisadvokaat',
    'quick.ai_lawyer_desc': 'Wetlike leiding',
    'quick.ai_visa_helper': 'KI Visum Assistent',
    'quick.ai_visa_helper_desc': 'Visum vereistes',
    'quick.ai_restaurant': 'KI Restaurant Bespreking',
    'quick.ai_restaurant_desc': 'Vind en bespreek naby',
    'quick.esim': 'eSIM Dienste',
    'quick.esim_desc': 'Bly wêreldwyd verbind',
    'quick.embassy': 'Ambassade Gids',
    'quick.embassy_desc': 'Amptelike kontakte',
    
    // Embassy Directory
    'embassy.title': 'Ambassade Gids',
    'embassy.description': 'Toegang tot amptelike ambassade webwerwe en reisadvies van groot lande',
    'embassy.visit_website': 'Besoek Webwerf',
    'embassy.travel_advice': 'Reisadvies',
    'embassy.register': 'Registreer Reis',
    'embassy.tip': 'Wenk: Registreer u reis by u ambassade vir noodhulp en veiligheidsopdaterings',
    
    // AI Assistant
    'ai.title': 'KI Reis Assistent',
    'ai.typing': 'KI is besig om te tik...',
    
    // Document Tracker
    'doc.title': 'Dokument Volger',
    'doc.passports': 'Paspoort',
    'doc.licenses': 'Lisensies',
    
    // Expense Tracker
    'expense.title': 'Besigheid Uitgawe Volger',
    
    // Smart Alerts
    'alerts.title': 'Slim Kennisgewings & Kennisgewings',
    'alerts.settings': 'Instellings',
    
    // Passport Manager
    'passport.title': 'Paspoort Bestuurder',
    
    // User Profile
    'profile.title': 'Gebruiker Profiel & Voorkeure',
    
    // Tax Residency
    'tax.title': 'Belasting Residensie & Voldoenings Sentrum',
    
    // Common
    'common.save': 'Stoor',
    'common.cancel': 'Kanselleer',
    'common.close': 'Sluit',
  },
  zh: {
    // App Header & Navigation
    'app.title': 'SmartNomad',
    'app.tagline': '您的全球生活数字助手',
    'header.profile': '个人资料',
    'header.profile_settings': '个人资料设置',
    'header.app_settings': '应用设置',
    'header.upgrade_plan': '升级计划',
    'header.privacy_data': '隐私和数据',
    'header.sign_out': '登出',
    'nav.dashboard': '仪表板',
    'nav.tracking': '旅行追踪',
    'nav.tax': '税务居住',
    'nav.visas': '签证管理',
    'nav.documents': '文件',
    'nav.health': '健康与疫苗',
    'nav.news': '旅行新闻',
    'nav.alerts': '智能提醒',
    'nav.services': '旅行服务',
    'nav.settings': '设置',
    'nav.help': '帮助与支持',
    'nav.footer_version': 'TravelTracker v2.0',
    'nav.footer_tagline': '全球合规',
    'stats.countries_tracked': '追踪国家',
    'stats.active_destinations': '活跃目的地',
    'stats.critical_alerts': '重要提醒',
    'stats.require_attention': '需要注意',
    'quick.title': '快速操作',
    'quick.add_country': '添加国家',
    'quick.add_country_desc': '追踪新目的地',
    'quick.upload_documents': '上传文件',
    'quick.upload_documents_desc': '添加护照和签证',
    'quick.check_visas': '检查签证',
    'quick.check_visas_desc': '查看签证状态',
    'quick.view_alerts': '查看提醒',
    'quick.view_alerts_desc': '检查通知',
    'quick.ai_doctor': 'AI旅行医生',
    'quick.ai_doctor_desc': '健康建议和疫苗',
    'quick.ai_lawyer': 'AI旅行律师',
    'quick.ai_lawyer_desc': '法律指导',
    'quick.ai_visa_helper': 'AI签证助手',
    'quick.ai_visa_helper_desc': '签证要求',
    'quick.ai_restaurant': 'AI餐厅预订',
    'quick.ai_restaurant_desc': '查找和预订附近餐厅',
    'quick.esim': 'eSIM服务',
    'quick.esim_desc': '全球保持连接',
    'quick.embassy': '大使馆目录',
    'quick.embassy_desc': '官方联系方式',
    'embassy.title': '大使馆目录',
    'embassy.description': '访问主要国家的官方大使馆网站和旅行建议',
    'embassy.visit_website': '访问网站',
    'embassy.travel_advice': '旅行建议',
    'embassy.register': '登记旅行',
    'embassy.tip': '提示：在大使馆登记您的旅行以获得紧急援助和安全更新',
    'ai.title': 'AI旅行助手',
    'ai.typing': 'AI正在输入...',
    'doc.title': '文件追踪',
    'doc.passports': '护照',
    'doc.licenses': '驾照',
    'expense.title': '商务费用追踪',
    'alerts.title': '智能提醒和通知',
    'alerts.settings': '设置',
    'passport.title': '护照管理',
    'profile.title': '用户资料和偏好',
    'tax.title': '税务居住和合规中心',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.close': '关闭',
  },
  fr: {
    // App Header & Navigation
    'app.title': 'SmartNomad',
    'app.tagline': 'Votre assistant numérique pour la vie mondiale',
    'header.profile': 'Profil',
    'header.profile_settings': 'Paramètres du profil',
    'header.app_settings': "Paramètres de l'application",
    'header.upgrade_plan': 'Mettre à niveau',
    'header.privacy_data': 'Confidentialité et données',
    'header.sign_out': 'Se déconnecter',
    'nav.dashboard': 'Tableau de bord',
    'nav.tracking': 'Suivi des voyages',
    'nav.tax': 'Résidence fiscale',
    'nav.visas': 'Gestionnaire de visas',
    'nav.documents': 'Documents',
    'nav.health': 'Santé et vaccins',
    'nav.news': 'Actualités voyage',
    'nav.alerts': 'Alertes intelligentes',
    'nav.services': 'Services de voyage',
    'nav.settings': 'Paramètres',
    'nav.help': 'Aide et support',
    'nav.footer_version': 'TravelTracker v2.0',
    'nav.footer_tagline': 'Restez conforme dans le monde entier',
    'stats.countries_tracked': 'Pays suivis',
    'stats.active_destinations': 'Destinations actives',
    'stats.critical_alerts': 'Alertes critiques',
    'stats.require_attention': 'Nécessitent une attention',
    'quick.title': 'Actions rapides',
    'quick.add_country': 'Ajouter un pays',
    'quick.add_country_desc': 'Suivre une nouvelle destination',
    'quick.upload_documents': 'Télécharger des documents',
    'quick.upload_documents_desc': 'Ajouter passeport et visas',
    'quick.check_visas': 'Vérifier les visas',
    'quick.check_visas_desc': 'Voir le statut des visas',
    'quick.view_alerts': 'Voir les alertes',
    'quick.view_alerts_desc': 'Vérifier les notifications',
    'quick.ai_doctor': 'Médecin de voyage IA',
    'quick.ai_doctor_desc': 'Conseils santé et vaccins',
    'quick.ai_lawyer': 'Avocat de voyage IA',
    'quick.ai_lawyer_desc': 'Conseils juridiques',
    'quick.ai_visa_helper': 'Assistant visa IA',
    'quick.ai_visa_helper_desc': 'Exigences de visa',
    'quick.ai_restaurant': 'Réservation restaurant IA',
    'quick.ai_restaurant_desc': 'Trouver et réserver à proximité',
    'quick.esim': 'Services eSIM',
    'quick.esim_desc': 'Restez connecté dans le monde entier',
    'quick.embassy': 'Annuaire des ambassades',
    'quick.embassy_desc': 'Contacts officiels',
    'embassy.title': 'Annuaire des ambassades',
    'embassy.description': 'Accédez aux sites Web officiels des ambassades et aux conseils aux voyageurs des principaux pays',
    'embassy.visit_website': 'Visiter le site',
    'embassy.travel_advice': 'Conseils de voyage',
    'embassy.register': 'Enregistrer le voyage',
    'embassy.tip': "Conseil : Enregistrez votre voyage auprès de votre ambassade pour une assistance d'urgence et des mises à jour de sécurité",
    'ai.title': 'Assistant de voyage IA',
    'ai.typing': "L'IA est en train d'écrire...",
    'doc.title': 'Suivi des documents',
    'doc.passports': 'Passeports',
    'doc.licenses': 'Permis',
    'expense.title': 'Suivi des dépenses professionnelles',
    'alerts.title': 'Alertes intelligentes et notifications',
    'alerts.settings': 'Paramètres',
    'passport.title': 'Gestionnaire de passeports',
    'profile.title': 'Profil utilisateur et préférences',
    'tax.title': 'Centre de résidence fiscale et de conformité',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.close': 'Fermer',
  },
  de: {
    // App Header & Navigation
    'app.title': 'SmartNomad',
    'app.tagline': 'Ihr digitaler Assistent für das globale Leben',
    'header.profile': 'Profil',
    'header.profile_settings': 'Profileinstellungen',
    'header.app_settings': 'App-Einstellungen',
    'header.upgrade_plan': 'Plan upgraden',
    'header.privacy_data': 'Datenschutz und Daten',
    'header.sign_out': 'Abmelden',
    'nav.dashboard': 'Dashboard',
    'nav.tracking': 'Reiseverfolgung',
    'nav.tax': 'Steuerlicher Wohnsitz',
    'nav.visas': 'Visa-Manager',
    'nav.documents': 'Dokumente',
    'nav.health': 'Gesundheit und Impfungen',
    'nav.news': 'Reisenachrichten',
    'nav.alerts': 'Intelligente Benachrichtigungen',
    'nav.services': 'Reisedienste',
    'nav.settings': 'Einstellungen',
    'nav.help': 'Hilfe und Support',
    'nav.footer_version': 'TravelTracker v2.0',
    'nav.footer_tagline': 'Weltweit konform bleiben',
    'stats.countries_tracked': 'Verfolgte Länder',
    'stats.active_destinations': 'Aktive Ziele',
    'stats.critical_alerts': 'Kritische Warnungen',
    'stats.require_attention': 'Erfordern Aufmerksamkeit',
    'quick.title': 'Schnellaktionen',
    'quick.add_country': 'Land hinzufügen',
    'quick.add_country_desc': 'Neues Ziel verfolgen',
    'quick.upload_documents': 'Dokumente hochladen',
    'quick.upload_documents_desc': 'Pass und Visa hinzufügen',
    'quick.check_visas': 'Visa überprüfen',
    'quick.check_visas_desc': 'Visumstatus anzeigen',
    'quick.view_alerts': 'Warnungen anzeigen',
    'quick.view_alerts_desc': 'Benachrichtigungen prüfen',
    'quick.ai_doctor': 'KI-Reisearzt',
    'quick.ai_doctor_desc': 'Gesundheitsberatung und Impfungen',
    'quick.ai_lawyer': 'KI-Reiseanwalt',
    'quick.ai_lawyer_desc': 'Rechtsberatung',
    'quick.ai_visa_helper': 'KI-Visum-Assistent',
    'quick.ai_visa_helper_desc': 'Visumanforderungen',
    'quick.ai_restaurant': 'KI-Restaurantbuchung',
    'quick.ai_restaurant_desc': 'In der Nähe finden und buchen',
    'quick.esim': 'eSIM-Dienste',
    'quick.esim_desc': 'Weltweit verbunden bleiben',
    'quick.embassy': 'Botschaftsverzeichnis',
    'quick.embassy_desc': 'Offizielle Kontakte',
    'embassy.title': 'Botschaftsverzeichnis',
    'embassy.description': 'Zugriff auf offizielle Botschaftswebsites und Reisehinweise wichtiger Länder',
    'embassy.visit_website': 'Website besuchen',
    'embassy.travel_advice': 'Reisehinweise',
    'embassy.register': 'Reise registrieren',
    'embassy.tip': 'Tipp: Registrieren Sie Ihre Reise bei Ihrer Botschaft für Notfallhilfe und Sicherheitsupdates',
    'ai.title': 'KI-Reiseassistent',
    'ai.typing': 'KI tippt...',
    'doc.title': 'Dokumentenverfolgung',
    'doc.passports': 'Reisepässe',
    'doc.licenses': 'Führerscheine',
    'expense.title': 'Geschäftsausgabenverfolgung',
    'alerts.title': 'Intelligente Benachrichtigungen',
    'alerts.settings': 'Einstellungen',
    'passport.title': 'Reisepass-Manager',
    'profile.title': 'Benutzerprofil und Einstellungen',
    'tax.title': 'Steuerlicher Wohnsitz und Compliance-Center',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.close': 'Schließen',
  },
  ar: {
    // App Header & Navigation
    'app.title': 'SmartNomad',
    'app.tagline': 'مساعدك الرقمي للحياة العالمية',
    'header.profile': 'الملف الشخصي',
    'header.profile_settings': 'إعدادات الملف الشخصي',
    'header.app_settings': 'إعدادات التطبيق',
    'header.upgrade_plan': 'ترقية الخطة',
    'header.privacy_data': 'الخصوصية والبيانات',
    'header.sign_out': 'تسجيل الخروج',
    'nav.dashboard': 'لوحة التحكم',
    'nav.tracking': 'تتبع السفر',
    'nav.tax': 'الإقامة الضريبية',
    'nav.visas': 'مدير التأشيرات',
    'nav.documents': 'المستندات',
    'nav.health': 'الصحة واللقاحات',
    'nav.news': 'أخبار السفر',
    'nav.alerts': 'التنبيهات الذكية',
    'nav.services': 'خدمات السفر',
    'nav.settings': 'الإعدادات',
    'nav.help': 'المساعدة والدعم',
    'nav.footer_version': 'TravelTracker v2.0',
    'nav.footer_tagline': 'ابقَ ملتزماً في جميع أنحاء العالم',
    'stats.countries_tracked': 'الدول المتتبعة',
    'stats.active_destinations': 'الوجهات النشطة',
    'stats.critical_alerts': 'التنبيهات الحرجة',
    'stats.require_attention': 'تتطلب الانتباه',
    'quick.title': 'إجراءات سريعة',
    'quick.add_country': 'إضافة دولة',
    'quick.add_country_desc': 'تتبع وجهة جديدة',
    'quick.upload_documents': 'تحميل المستندات',
    'quick.upload_documents_desc': 'إضافة جواز السفر والتأشيرات',
    'quick.check_visas': 'التحقق من التأشيرات',
    'quick.check_visas_desc': 'عرض حالة التأشيرة',
    'quick.view_alerts': 'عرض التنبيهات',
    'quick.view_alerts_desc': 'التحقق من الإشعارات',
    'quick.ai_doctor': 'طبيب السفر بالذكاء الاصطناعي',
    'quick.ai_doctor_desc': 'نصائح صحية ولقاحات',
    'quick.ai_lawyer': 'محامي السفر بالذكاء الاصطناعي',
    'quick.ai_lawyer_desc': 'إرشادات قانونية',
    'quick.ai_visa_helper': 'مساعد التأشيرة بالذكاء الاصطناعي',
    'quick.ai_visa_helper_desc': 'متطلبات التأشيرة',
    'quick.ai_restaurant': 'حجز المطاعم بالذكاء الاصطناعي',
    'quick.ai_restaurant_desc': 'البحث والحجز في مكان قريب',
    'quick.esim': 'خدمات eSIM',
    'quick.esim_desc': 'ابقَ متصلاً في جميع أنحاء العالم',
    'quick.embassy': 'دليل السفارات',
    'quick.embassy_desc': 'جهات الاتصال الرسمية',
    'embassy.title': 'دليل السفارات',
    'embassy.description': 'الوصول إلى المواقع الرسمية للسفارات ونصائح السفر من الدول الرئيسية',
    'embassy.visit_website': 'زيارة الموقع',
    'embassy.travel_advice': 'نصائح السفر',
    'embassy.register': 'تسجيل السفر',
    'embassy.tip': 'نصيحة: سجل رحلتك لدى سفارتك للحصول على المساعدة في حالات الطوارئ والتحديثات الأمنية',
    'ai.title': 'مساعد السفر بالذكاء الاصطناعي',
    'ai.typing': 'الذكاء الاصطناعي يكتب...',
    'doc.title': 'تتبع المستندات',
    'doc.passports': 'جوازات السفر',
    'doc.licenses': 'رخص القيادة',
    'expense.title': 'تتبع نفقات الأعمال',
    'alerts.title': 'التنبيهات الذكية والإشعارات',
    'alerts.settings': 'الإعدادات',
    'passport.title': 'مدير جوازات السفر',
    'profile.title': 'ملف المستخدم والتفضيلات',
    'tax.title': 'مركز الإقامة الضريبية والامتثال',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.close': 'إغلاق',
  },
  ja: {
    // App Header & Navigation
    'app.title': 'SmartNomad',
    'app.tagline': 'グローバルライフのためのデジタルアシスタント',
    'header.profile': 'プロフィール',
    'header.profile_settings': 'プロフィール設定',
    'header.app_settings': 'アプリ設定',
    'header.upgrade_plan': 'プランをアップグレード',
    'header.privacy_data': 'プライバシーとデータ',
    'header.sign_out': 'サインアウト',
    'nav.dashboard': 'ダッシュボード',
    'nav.tracking': '旅行追跡',
    'nav.tax': '税務居住',
    'nav.visas': 'ビザ管理',
    'nav.documents': '書類',
    'nav.health': '健康とワクチン',
    'nav.news': '旅行ニュース',
    'nav.alerts': 'スマート通知',
    'nav.services': '旅行サービス',
    'nav.settings': '設定',
    'nav.help': 'ヘルプとサポート',
    'nav.footer_version': 'TravelTracker v2.0',
    'nav.footer_tagline': '世界中でコンプライアンスを維持',
    'stats.countries_tracked': '追跡中の国',
    'stats.active_destinations': 'アクティブな目的地',
    'stats.critical_alerts': '重要な通知',
    'stats.require_attention': '注意が必要',
    'quick.title': 'クイックアクション',
    'quick.add_country': '国を追加',
    'quick.add_country_desc': '新しい目的地を追跡',
    'quick.upload_documents': '書類をアップロード',
    'quick.upload_documents_desc': 'パスポートとビザを追加',
    'quick.check_visas': 'ビザを確認',
    'quick.check_visas_desc': 'ビザステータスを表示',
    'quick.view_alerts': '通知を表示',
    'quick.view_alerts_desc': '通知を確認',
    'quick.ai_doctor': 'AI旅行ドクター',
    'quick.ai_doctor_desc': '健康アドバイスとワクチン',
    'quick.ai_lawyer': 'AI旅行弁護士',
    'quick.ai_lawyer_desc': '法的ガイダンス',
    'quick.ai_visa_helper': 'AIビザヘルパー',
    'quick.ai_visa_helper_desc': 'ビザ要件',
    'quick.ai_restaurant': 'AIレストラン予約',
    'quick.ai_restaurant_desc': '近くを検索して予約',
    'quick.esim': 'eSIMサービス',
    'quick.esim_desc': '世界中で接続を維持',
    'quick.embassy': '大使館ディレクトリ',
    'quick.embassy_desc': '公式連絡先',
    'embassy.title': '大使館ディレクトリ',
    'embassy.description': '主要国の公式大使館ウェブサイトと旅行アドバイスにアクセス',
    'embassy.visit_website': 'ウェブサイトを訪問',
    'embassy.travel_advice': '旅行アドバイス',
    'embassy.register': '旅行を登録',
    'embassy.tip': 'ヒント：緊急支援とセキュリティ更新のために、大使館に旅行を登録してください',
    'ai.title': 'AI旅行アシスタント',
    'ai.typing': 'AIが入力中...',
    'doc.title': '書類追跡',
    'doc.passports': 'パスポート',
    'doc.licenses': '運転免許証',
    'expense.title': 'ビジネス経費追跡',
    'alerts.title': 'スマート通知とお知らせ',
    'alerts.settings': '設定',
    'passport.title': 'パスポートマネージャー',
    'profile.title': 'ユーザープロフィールと設定',
    'tax.title': '税務居住とコンプライアンスセンター',
    'common.save': '保存',
    'common.cancel': 'キャンセル',
    'common.close': '閉じる',
  },
  it: {
    // App Header & Navigation
    'app.title': 'SmartNomad',
    'app.tagline': 'Il tuo assistente digitale per la vita globale',
    'header.profile': 'Profilo',
    'header.profile_settings': 'Impostazioni profilo',
    'header.app_settings': "Impostazioni dell'app",
    'header.upgrade_plan': 'Aggiorna piano',
    'header.privacy_data': 'Privacy e dati',
    'header.sign_out': 'Esci',
    'nav.dashboard': 'Dashboard',
    'nav.tracking': 'Tracciamento viaggi',
    'nav.tax': 'Residenza fiscale',
    'nav.visas': 'Gestore visti',
    'nav.documents': 'Documenti',
    'nav.health': 'Salute e vaccini',
    'nav.news': 'Notizie di viaggio',
    'nav.alerts': 'Avvisi intelligenti',
    'nav.services': 'Servizi di viaggio',
    'nav.settings': 'Impostazioni',
    'nav.help': 'Aiuto e supporto',
    'nav.footer_version': 'TravelTracker v2.0',
    'nav.footer_tagline': 'Rimani conforme in tutto il mondo',
    'stats.countries_tracked': 'Paesi tracciati',
    'stats.active_destinations': 'Destinazioni attive',
    'stats.critical_alerts': 'Avvisi critici',
    'stats.require_attention': 'Richiedono attenzione',
    'quick.title': 'Azioni rapide',
    'quick.add_country': 'Aggiungi paese',
    'quick.add_country_desc': 'Traccia nuova destinazione',
    'quick.upload_documents': 'Carica documenti',
    'quick.upload_documents_desc': 'Aggiungi passaporto e visti',
    'quick.check_visas': 'Controlla visti',
    'quick.check_visas_desc': 'Visualizza stato visto',
    'quick.view_alerts': 'Visualizza avvisi',
    'quick.view_alerts_desc': 'Controlla notifiche',
    'quick.ai_doctor': 'Medico di viaggio AI',
    'quick.ai_doctor_desc': 'Consigli sanitari e vaccini',
    'quick.ai_lawyer': 'Avvocato di viaggio AI',
    'quick.ai_lawyer_desc': 'Orientamento legale',
    'quick.ai_visa_helper': 'Assistente visti AI',
    'quick.ai_visa_helper_desc': 'Requisiti visto',
    'quick.ai_restaurant': 'Prenotazione ristoranti AI',
    'quick.ai_restaurant_desc': 'Trova e prenota nelle vicinanze',
    'quick.esim': 'Servizi eSIM',
    'quick.esim_desc': 'Rimani connesso in tutto il mondo',
    'quick.embassy': 'Elenco ambasciate',
    'quick.embassy_desc': 'Contatti ufficiali',
    'embassy.title': 'Elenco ambasciate',
    'embassy.description': 'Accedi ai siti web ufficiali delle ambasciate e ai consigli di viaggio dei principali paesi',
    'embassy.visit_website': 'Visita il sito',
    'embassy.travel_advice': 'Consigli di viaggio',
    'embassy.register': 'Registra viaggio',
    'embassy.tip': 'Suggerimento: Registra il tuo viaggio presso la tua ambasciata per assistenza di emergenza e aggiornamenti sulla sicurezza',
    'ai.title': 'Assistente di viaggio AI',
    'ai.typing': "L'AI sta scrivendo...",
    'doc.title': 'Tracciamento documenti',
    'doc.passports': 'Passaporti',
    'doc.licenses': 'Patenti',
    'expense.title': 'Tracciamento spese aziendali',
    'alerts.title': 'Avvisi intelligenti e notifiche',
    'alerts.settings': 'Impostazioni',
    'passport.title': 'Gestore passaporti',
    'profile.title': 'Profilo utente e preferenze',
    'tax.title': 'Centro di residenza fiscale e conformità',
    'common.save': 'Salva',
    'common.cancel': 'Annulla',
    'common.close': 'Chiudi',
  },
  ko: {
    // App Header & Navigation
    'app.title': 'SmartNomad',
    'app.tagline': '글로벌 생활을 위한 디지털 어시스턴트',
    'header.profile': '프로필',
    'header.profile_settings': '프로필 설정',
    'header.app_settings': '앱 설정',
    'header.upgrade_plan': '플랜 업그레이드',
    'header.privacy_data': '개인정보 및 데이터',
    'header.sign_out': '로그아웃',
    'nav.dashboard': '대시보드',
    'nav.tracking': '여행 추적',
    'nav.tax': '세금 거주지',
    'nav.visas': '비자 관리',
    'nav.documents': '문서',
    'nav.health': '건강 및 백신',
    'nav.news': '여행 뉴스',
    'nav.alerts': '스마트 알림',
    'nav.services': '여행 서비스',
    'nav.settings': '설정',
    'nav.help': '도움말 및 지원',
    'nav.footer_version': 'TravelTracker v2.0',
    'nav.footer_tagline': '전 세계적으로 준수 유지',
    'stats.countries_tracked': '추적 중인 국가',
    'stats.active_destinations': '활성 목적지',
    'stats.critical_alerts': '중요 알림',
    'stats.require_attention': '주의 필요',
    'quick.title': '빠른 작업',
    'quick.add_country': '국가 추가',
    'quick.add_country_desc': '새 목적지 추적',
    'quick.upload_documents': '문서 업로드',
    'quick.upload_documents_desc': '여권 및 비자 추가',
    'quick.check_visas': '비자 확인',
    'quick.check_visas_desc': '비자 상태 보기',
    'quick.view_alerts': '알림 보기',
    'quick.view_alerts_desc': '알림 확인',
    'quick.ai_doctor': 'AI 여행 의사',
    'quick.ai_doctor_desc': '건강 조언 및 백신',
    'quick.ai_lawyer': 'AI 여행 변호사',
    'quick.ai_lawyer_desc': '법률 안내',
    'quick.ai_visa_helper': 'AI 비자 도우미',
    'quick.ai_visa_helper_desc': '비자 요구사항',
    'quick.ai_restaurant': 'AI 레스토랑 예약',
    'quick.ai_restaurant_desc': '근처 검색 및 예약',
    'quick.esim': 'eSIM 서비스',
    'quick.esim_desc': '전 세계적으로 연결 유지',
    'quick.embassy': '대사관 디렉토리',
    'quick.embassy_desc': '공식 연락처',
    'embassy.title': '대사관 디렉토리',
    'embassy.description': '주요 국가의 공식 대사관 웹사이트 및 여행 조언 액세스',
    'embassy.visit_website': '웹사이트 방문',
    'embassy.travel_advice': '여행 조언',
    'embassy.register': '여행 등록',
    'embassy.tip': '팁: 긴급 지원 및 보안 업데이트를 위해 대사관에 여행을 등록하세요',
    'ai.title': 'AI 여행 어시스턴트',
    'ai.typing': 'AI가 입력 중입니다...',
    'doc.title': '문서 추적',
    'doc.passports': '여권',
    'doc.licenses': '운전면허증',
    'expense.title': '비즈니스 비용 추적',
    'alerts.title': '스마트 알림 및 알림',
    'alerts.settings': '설정',
    'passport.title': '여권 관리자',
    'profile.title': '사용자 프로필 및 설정',
    'tax.title': '세금 거주지 및 준수 센터',
    'common.save': '저장',
    'common.cancel': '취소',
    'common.close': '닫기',
  },
};

// Add comprehensive translation keys for all languages
const getTranslation = (key: string, translations: Record<string, string>): string => {
  return translations[key] || key;
};

const commonTranslations = {
  'common.free': {
    en: 'Free', es: 'Gratis', pt: 'Grátis', zh: '免费', fr: 'Gratuit', de: 'Kostenlos', 
    ar: 'مجاني', ja: '無料', it: 'Gratis', ko: '무료', hi: 'मुफ़्त', sw: 'Bure', af: 'Gratis'
  },
  'doc.track_description': {
    en: 'Track your passports and driving licenses with expiry monitoring',
    es: 'Rastree sus pasaportes y licencias de conducir con monitoreo de vencimiento',
    pt: 'Rastreie seus passaportes e carteiras de motorista com monitoramento de validade',
    zh: '跟踪您的护照和驾照并监控到期时间',
    fr: 'Suivez vos passeports et permis de conduire avec surveillance des expirations',
    de: 'Verfolgen Sie Ihre Reisepässe und Führerscheine mit Ablaufüberwachung',
    ar: 'تتبع جوازات السفر ورخص القيادة الخاصة بك مع مراقبة انتهاء الصلاحية',
    ja: 'パスポートと運転免許証を有効期限監視で追跡',
    it: 'Traccia i tuoi passaporti e patenti con monitoraggio della scadenza',
    ko: '여권 및 운전면허증을 만료 모니터링으로 추적',
    hi: 'समाप्ति निगरानी के साथ अपने पासपोर्ट और ड्राइविंग लाइसेंस ट्रैक करें',
    sw: 'Fuatilia pasi na leseni zako za kuendesha na ufuatiliaji wa kumalizika',
    af: 'Volg u paspoort en rybewys met vervaldatum monitering'
  },
  'doc.no_passports': {
    en: 'No passports tracked yet', es: 'Aún no se rastrean pasaportes', pt: 'Nenhum passaporte rastreado ainda',
    zh: '尚未追踪任何护照', fr: 'Aucun passeport suivi pour le moment', de: 'Noch keine Reisepässe verfolgt',
    ar: 'لم يتم تتبع جوازات سفر بعد', ja: 'まだパスポートを追跡していません', it: 'Nessun passaporto tracciato ancora',
    ko: '아직 추적된 여권이 없습니다', hi: 'अभी तक कोई पासपोर्ट ट्रैक नहीं किया गया',
    sw: 'Hakuna pasi zilizofuatiliwa bado', af: 'Nog geen paspoort opgevolg nie'
  },
  'doc.no_licenses': {
    en: 'No licenses tracked yet', es: 'Aún no se rastrean licencias', pt: 'Nenhuma licença rastreada ainda',
    zh: '尚未追踪任何驾照', fr: 'Aucun permis suivi pour le moment', de: 'Noch keine Führerscheine verfolgt',
    ar: 'لم يتم تتبع رخص بعد', ja: 'まだ免許証を追跡していません', it: 'Nessuna patente tracciata ancora',
    ko: '아직 추적된 면허증이 없습니다', hi: 'अभी तक कोई लाइसेंस ट्रैक नहीं किया गया',
    sw: 'Hakuna leseni zilizofuatiliwa bado', af: 'Nog geen lisensies opgevolg nie'
  },
  'doc.add_passport': {
    en: 'Add Passport', es: 'Agregar pasaporte', pt: 'Adicionar passaporte', zh: '添加护照',
    fr: 'Ajouter un passeport', de: 'Reisepass hinzufügen', ar: 'إضافة جواز سفر',
    ja: 'パスポートを追加', it: 'Aggiungi passaporto', ko: '여권 추가', hi: 'पासपोर्ट जोड़ें',
    sw: 'Ongeza Pasi', af: 'Voeg Paspoort By'
  },
  'doc.add_license': {
    en: 'Add License', es: 'Agregar licencia', pt: 'Adicionar licença', zh: '添加驾照',
    fr: 'Ajouter un permis', de: 'Führerschein hinzufügen', ar: 'إضافة رخصة',
    ja: '免許証を追加', it: 'Aggiungi patente', ko: '면허증 추가', hi: 'लाइसेंस जोड़ें',
    sw: 'Ongeza Leseni', af: 'Voeg Lisensie By'
  },
  'doc.expired': {
    en: 'Expired', es: 'Vencido', pt: 'Expirado', zh: '已过期', fr: 'Expiré', de: 'Abgelaufen',
    ar: 'منتهي الصلاحية', ja: '期限切れ', it: 'Scaduto', ko: '만료됨', hi: 'समाप्त', sw: 'Imeisha', af: 'Verstreke'
  },
  'doc.expiring_soon': {
    en: 'Expiring Soon', es: 'Vence pronto', pt: 'Expirando em breve', zh: '即将过期',
    fr: 'Expire bientôt', de: 'Läuft bald ab', ar: 'تنتهي قريباً', ja: 'まもなく期限切れ',
    it: 'In scadenza', ko: '곧 만료', hi: 'जल्द समाप्त हो रहा है', sw: 'Inaisha Hivi Karibuni', af: 'Verval Binnekort'
  },
  'doc.valid': {
    en: 'Valid', es: 'Válido', pt: 'Válido', zh: '有效', fr: 'Valide', de: 'Gültig',
    ar: 'صالح', ja: '有効', it: 'Valido', ko: '유효함', hi: 'वैध', sw: 'Halali', af: 'Geldig'
  },
  'doc.expires': {
    en: 'Expires', es: 'Vence', pt: 'Expira', zh: '到期', fr: 'Expire', de: 'Läuft ab',
    ar: 'تنتهي', ja: '期限', it: 'Scade', ko: '만료', hi: 'समाप्त होता है', sw: 'Inaisha', af: 'Verval'
  },
  'doc.country_state': {
    en: 'Country/State', es: 'País/Estado', pt: 'País/Estado', zh: '国家/州',
    fr: 'Pays/État', de: 'Land/Bundesland', ar: 'البلد/الولاية', ja: '国/州',
    it: 'Paese/Stato', ko: '국가/주', hi: 'देश/राज्य', sw: 'Nchi/Jimbo', af: 'Land/Staat'
  },
  'doc.license_class': {
    en: 'License Class', es: 'Clase de licencia', pt: 'Classe de licença', zh: '驾照类型',
    fr: 'Classe de permis', de: 'Führerscheinklasse', ar: 'فئة الرخصة', ja: '免許クラス',
    it: 'Classe patente', ko: '면허 등급', hi: 'लाइसेंस वर्ग', sw: 'Darasa la Leseni', af: 'Lisensie Klas'
  },
  'doc.issue_date': {
    en: 'Issue Date', es: 'Fecha de emisión', pt: 'Data de emissão', zh: '签发日期',
    fr: "Date d'émission", de: 'Ausstellungsdatum', ar: 'تاريخ الإصدار', ja: '発行日',
    it: 'Data di emissione', ko: '발급일', hi: 'जारी करने की तिथि', sw: 'Tarehe ya Kutolewa', af: 'Uitgiftedatum'
  },
  'doc.expiry_date': {
    en: 'Expiry Date', es: 'Fecha de vencimiento', pt: 'Data de validade', zh: '到期日期',
    fr: "Date d'expiration", de: 'Ablaufdatum', ar: 'تاريخ انتهاء الصلاحية', ja: '有効期限',
    it: 'Data di scadenza', ko: '만료일', hi: 'समाप्ति तिथि', sw: 'Tarehe ya Kumalizika', af: 'Vervaldatum'
  },
  'doc.issuing_authority': {
    en: 'Issuing Authority', es: 'Autoridad emisora', pt: 'Autoridade emissora', zh: '签发机构',
    fr: "Autorité émettrice", de: 'Ausstellende Behörde', ar: 'جهة الإصدار', ja: '発行機関',
    it: 'Autorità emittente', ko: '발급 기관', hi: 'जारी करने वाला प्राधिकरण', sw: 'Mamlaka ya Kutoa', af: 'Uitreik Owerheid'
  },
  'doc.notes': {
    en: 'Notes', es: 'Notas', pt: 'Notas', zh: '备注', fr: 'Notes', de: 'Notizen',
    ar: 'ملاحظات', ja: 'メモ', it: 'Note', ko: '메모', hi: 'नोट्स', sw: 'Maelezo', af: 'Nota'
  },
  'doc.missing_info': {
    en: 'Missing information', es: 'Falta información', pt: 'Informação ausente', zh: '信息缺失',
    fr: 'Information manquante', de: 'Fehlende Informationen', ar: 'معلومات مفقودة', ja: '情報が不足しています',
    it: 'Informazioni mancanti', ko: '정보 누락', hi: 'जानकारी गायब है', sw: 'Habari inayokosekana', af: 'Ontbrekende inligting'
  },
  'doc.fill_required': {
    en: 'Please fill in all required fields', es: 'Por favor complete todos los campos requeridos',
    pt: 'Por favor, preencha todos os campos obrigatórios', zh: '请填写所有必填字段',
    fr: 'Veuillez remplir tous les champs requis', de: 'Bitte füllen Sie alle erforderlichen Felder aus',
    ar: 'يرجى ملء جميع الحقول المطلوبة', ja: 'すべての必須フィールドに入力してください',
    it: 'Si prega di compilare tutti i campi obbligatori', ko: '모든 필수 필드를 입력하세요',
    hi: 'कृपया सभी आवश्यक फ़ील्ड भरें', sw: 'Tafadhali jaza sehemu zote zinazohitajika', af: 'Vul asseblief alle vereiste velde in'
  },
};

Object.keys(translations).forEach(lang => {
  Object.keys(commonTranslations).forEach(key => {
    if (!translations[lang][key]) {
      translations[lang][key] = commonTranslations[key][lang] || commonTranslations[key]['en'];
    }
  });
});

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<string>(() => {
    const saved = localStorage.getItem('app_language');
    return saved && ['en', 'es', 'pt', 'zh', 'fr', 'de', 'ar', 'ja', 'it', 'ko', 'hi', 'sw', 'af'].includes(saved) ? saved : 'en';
  });

  useEffect(() => {
    localStorage.setItem('app_language', currentLanguage);
  }, [currentLanguage]);

  const t = (key: string): string => {
    return translations[currentLanguage]?.[key] || translations['en']?.[key] || key;
  };

  const setLanguage = (code: string) => {
    if (['en', 'es', 'pt', 'zh', 'fr', 'de', 'ar', 'ja', 'it', 'ko', 'hi', 'sw', 'af'].includes(code)) {
      setCurrentLanguage(code);
    }
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
